[package]
name = "trenchioWT"
version = "0.1.0"
edition = "2021"

[dependencies]
url = "2.5.0"
solana-client = "1.17"
solana-sdk = "1.17"
tokio = { version = "1.36", features = ["full"] }
tokio-tungstenite = "0.21"
